version: '2'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - 'zookeeper_data:/data'

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: gavluk-laptop
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - kafka_data:/kafka
      - /var/run/docker.sock:/var/run/docker.sock

  kafdrop:
    depends_on:
        - kafka
    restart: on-failure
    image: obsidiandynamics/kafdrop:latest
    ports:
        - '9093:9000'
    environment:
        KAFKA_BROKERCONNECT: 'kafka:9092'
        JVM_OPTS: "-Xms32M -Xmx64M"
        SERVER_SERVLET_CONTEXTPATH: "/"
volumes:
  zookeeper_data:
  kafka_data:
