apiVersion: v1
kind: Pod
metadata:
  name: python-utils
spec:
  containers:
  - name: python-utils
    image: python:3.9.18
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]